core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix: /

logout:
    path: /logout
